version: 2
updates:
  - package-ecosystem: maven
    directory: /
    schedule:
      interval: daily
      time: '03:00'
      timezone: Europe/Paris
    open-pull-requests-limit: 99
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
      time: '03:00'
      timezone: Europe/Paris
    open-pull-requests-limit: 99
