name: Build & Release

on:
  push:
    tags:
      - 'v*'

jobs:
  container:
    runs-on: ubuntu-latest
    container:
      image: 'jgraph/drawio-builder:latest'
    steps:
    - name: Checkout reposistory
      uses: actions/checkout@v3
      with:
        ref: 'release'
    - name: Build
      run: |
        sed -i "s/USERNAME_HERE/${{secrets.GH_PKG_USERNAME}}/g" /root/.m2/settings.xml
        sed -i "s/TOKEN_HERE/${{secrets.GH_PKG_ACCESS_KEY}}/g" /root/.m2/settings.xml
        export PLANTUML_VERSION=`echo $GITHUB_REF | awk 'BEGIN { FS = "/" } ; { print substr($3, 2, length($3)) }'`
        ant mvn-deploy-jar
